### ISSUE TITLE
Screenshot API

### ISSUE THREAD

**Issue by Kauabunga** [brainly/nodejs-onesky-utils#24]
Add screenshot to library following OneSky API @ https://github.com/onesky/api-documentation-platform/blob/master/resources/screenshot.md

**Comment by Kauabunga** [comment]
Have this feature sitting on a pull request @ https://github.com/brainly/nodejs-onesky-utils/pull/25

**Comment by kdzwinel** [comment]
Merged and published in 1.3.0
Thank you!
