### ISSUE TITLE
npm audit shows vulnerabilities

### ISSUE THREAD

**Issue by andzejsw** [brainly/nodejs-onesky-utils#33]
npm audit shows vulnerabilities in lodash dependency:

Low             Prototype Pollution                                                   
Package         lodash                                                                                               
Patched in      >=4.17.5                                                                          
Dependency of   @brainly/onesky-utils [dev]                                                         
Path            @brainly/onesky-utils > request-promise > lodash                                                                    
More info       https://nodesecurity.io/advisories/577

Moderate        Prototype Pollution                                            
Package         lodash                                                                                           
Patched in      >=4.17.11                                                                                                                    
Dependency of   @brainly/onesky-utils [dev]                                                                                                        
Path            @brainly/onesky-utils > request-promise > lodash                                                                                
More info       https://nodesecurity.io/advisories/782

**Comment by elidupuis** [comment]
See #32. The maintainers have been unresponsive so far.

@SebastianCzoch Is it safe to say this project is dead? Maybe some community members would be able to take over?

/cc @andzejsw @smoke

**Comment by SebastianCzoch** [comment]
@andzejsw @elidupuis sorry for huge delay, fixed in #34
